### PR TITLE
Multiple GSI Support

### PR DESCRIPTION
**Pull request by ferrants**

### CODE REVIEW

**Comment by ankit2002** [comment]
Hey, Do you guys have any example for this adapter.

**Comment by ferrants** [comment]
@ankit2002 Yes, see the readme in the repo

**Comment by ankit2002** [comment]
Thanks for the response. I have done the setting part in Connections and models. But I could not understand how does i have to create a table or fetch a tables details.

**Comment by ferrants** [comment]
I create the tables using cloudformation and then use this to point to those tables

**Comment by ankit2002** [comment]
Can we create the table from the code itself. Please let me know if you have any running code. Because i am trying to use sails js with dynamodb.

**Comment by ferrants** [comment]
Yes. It just tries to create them if they don't exist. Not sure if it sets up all indexes correctly or how it sets up capacities. Yeah, this library is for using sails with dynamodb.

**Pull request merged**
